"""Fraud signal — async scored output from brain-* services.

Per DECISIONS.md D-004: brain services publish to `fraud.signals.v1` and the
decisions service consumes. This is the asynchronous edge of the scoring
pipeline; the synchronous gRPC scoring path stays available for the inline
tier where decisions has to block on a score.
"""

from __future__ import annotations

from typing import ClassVar

from pydantic import BaseModel, ConfigDict, Field

from fraudnet.schemas.types import RiskScore, Severity, Subject


class FeatureContribution(BaseModel):
    """Per-feature attribution for a SignalEventV1.

    Mirrors the wire format `fraudnet.xai.FeatureContribution` produces so
    that brain services can pass it through as-is. Three numbers per
    feature:
      - `value`     the feature value at scoring time
      - `baseline`  the typical value for this entity / cohort (e.g. p95)
      - `weight`    the contribution to the score in [-1, 1]; sign indicates
                    direction (positive = pushes score up = riskier)
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    feature: str = Field(min_length=1, max_length=64)
    value: float
    baseline: float | None = None
    weight: float = Field(ge=-1.0, le=1.0)


class SignalEventV1(BaseModel):
    """One scored signal from a brain-* service.

    Multiple signals per subject are expected over time. The decisions
    service applies suppression on `suppression_key` to avoid alert storms.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    topic: ClassVar[str] = "fraud.signals.v1"

    event_id: str = Field(min_length=8, max_length=64)
    event_ts_ms: int = Field(ge=0)
    ingest_ts_ms: int = Field(ge=0)
    source: str = Field(min_length=1, max_length=64)
    tenant_id: str = Field(default="mtn-ghana", min_length=1)

    signal_kind: str = Field(min_length=1, max_length=64)  # e.g. 'voice.velocity_burst'
    subject: Subject
    score: RiskScore
    severity: Severity

    # Optional structured evidence (feature attribution, top URLs, anomaly
    # vectors). Keep keys primitive — these flow into Iceberg.
    evidence: dict[str, str | int | float | bool] = Field(default_factory=dict)

    # Suppression key lets decisions dedup repeat alerts. Conventional shape:
    # "<tenant>:<subject_kind>:<subject_id>:<signal_kind>".
    suppression_key: str | None = None

    # Explainability layer (best-of-breed sprint). Top-N feature
    # contributions ranked by absolute weight; the human-readable sentence
    # is generated by `fraudnet.xai.explain_signal`. Both are PII-free —
    # never include raw subject IDs.
    feature_contributions: list[FeatureContribution] = Field(default_factory=list)
    explanation_text: str | None = Field(default=None, max_length=512)
